name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests (headless)
        run: npm run cy:ci
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
          LOCKED_OUT_USERNAME: ${{ secrets.LOCKED_OUT_USERNAME }}

      - name: Generate Mochawesome HTML report
        run: npm run report:generate

      - name: Upload Mochawesome HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

